version: "3.8"

services:
  db:
    container_name: db-dev
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=LC_KANDY
      - MYSQL_ROOT_PASSWORD=root
    # restart: always
    ports:
      - 3306:3306
    networks:
      - private
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  server:
    container_name: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public
      - private
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_DB=LC_KANDY
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: ./server
        target: /app
      - /app/node_modules

  client:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - public
    volumes:
      - type: bind
        source: ./client
        target: /app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

networks:
  public:
  private:
