name : CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Loggins into Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -password_stdin $DOCKER_PASSWORD

    - name: building the docker image
      run: docker-compose build co227

    - name: tagging docker image
      run: docker tag co227 dinuka029/co227:latest

    - name: Pushing the image to docker hub
      run: docker push dinuka029/co227:latest