name : CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Logging into Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: building the docker image
      run: docker-compose build -t dimg

    - name: Sleep for 10 seconds
      run: sleep 10

    - name: tagging docker image
      run: docker tag dimg:latest dinuka029/co227:latest

    - name: Check if the `dimg` image is built and tagged correctly
      run: docker images | grep dimg:latest

    - name: Check the current Docker context
      run: docker context

    - name: Check the permissions for the `dimg` image
      run: docker inspect dimg

    - name: Pushing the image to docker hub
      run: docker push dinuka029/co227:dimg